title: Hữu Tuấn
description: Blog about IT and Cyber Security
author: Thân Hữu Tuấn
logo: /static/img/huutuan.png
github: https://github.com/thanhuutuan
about: Cyber Security

baseurl: "https://thanhuutuan.github.io"
url: "https://thanhuutuan.github.io"

allowsearch: true

disqus_shortname: huutuan
google_analytics: UA-49863231-2

share:
  twitter_username: \huutuanbg97
  fb_appid: 100003882696042


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
